export const languages = [
  { name: 'Afrikaans', code: 'af' },
  { name: 'Albanian', code: 'sq' },
  { name: 'Amharic', code: 'am' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Armenian', code: 'hy' },
  { name: 'Azerbaijani', code: 'az' },
  { name: 'Basque', code: 'eu' },
  { name: 'Belarusian', code: 'be' },
  { name: 'Bengali', code: 'bn' },
  { name: 'Bhojpuri', code: 'bho' },
  { name: 'Bosnian', code: 'bs' },
  { name: 'Bulgarian', code: 'bg' },
  { name: 'Catalan', code: 'ca' },
  { name: 'Cebuano', code: 'ceb' },
  { name: 'Chichewa', code: 'ny' },
  { name: 'Chinese (Simplified)', code: 'zh' },
  { name: 'Chinese (Traditional)', code: 'zh-TW' },
  { name: 'Corsican', code: 'co' },
  { name: 'Croatian', code: 'hr' },
  { name: 'Czech', code: 'cs' },
  { name: 'Danish', code: 'da' },
  { name: 'Dutch', code: 'nl' },
  { name: 'English', code: 'en' },
  { name: 'Esperanto', code: 'eo' },
  { name: 'Estonian', code: 'et' },
  { name: 'Filipino', code: 'tl' },
  { name: 'Finnish', code: 'fi' },
  { name: 'French', code: 'fr' },
  { name: 'Frisian', code: 'fy' },
  { name: 'Galician', code: 'gl' },
  { name: 'Georgian', code: 'ka' },
  { name: 'German', code: 'de' },
  { name: 'Greek', code: 'el' },
  { name: 'Gujarati', code: 'gu' },
  { name: 'Haitian Creole', code: 'ht' },
  { name: 'Hausa', code: 'ha' },
  { name: 'Hawaiian', code: 'haw' },
  { name: 'Hebrew', code: 'iw' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Hmong', code: 'hmn' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Icelandic', code: 'is' },
  { name: 'Igbo', code: 'ig' },
  { name: 'Indonesian', code: 'id' },
  { name: 'Irish', code: 'ga' },
  { name: 'Italian', code: 'it' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Javanese', code: 'jw' },
  { name: 'Kannada', code: 'kn' },
  { name: 'Kazakh', code: 'kk' },
  { name: 'Khmer', code: 'km' },
  { name: 'Korean', code: 'ko' },
  { name: 'Kurdish (Kurmanji)', code: 'ku' },
  { name: 'Kyrgyz', code: 'ky' },
  { name: 'Lao', code: 'lo' },
  { name: 'Latin', code: 'la' },
  { name: 'Latvian', code: 'lv' },
  { name: 'Lithuanian', code: 'lt' },
  { name: 'Luxembourgish', code: 'lb' },
  { name: 'Macedonian', code: 'mk' },
  { name: 'Malagasy', code: 'mg' },
  { name: 'Malay', code: 'ms' },
  { name: 'Malayalam', code: 'ml' },
  { name: 'Maltese', code: 'mt' },
  { name: 'Maori', code: 'mi' },
  { name: 'Marathi', code: 'mr' },
  { name: 'Mongolian', code: 'mn' },
  { name: 'Myanmar (Burmese)', code: 'my' },
  { name: 'Nepali', code: 'ne' },
  { name: 'Norwegian', code: 'no' },
  { name: 'Odia (Oriya)', code: 'or' },
  { name: 'Pashto', code: 'ps' },
  { name: 'Persian', code: 'fa' },
  { name: 'Polish', code: 'pl' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Punjabi', code: 'pa' },
  { name: 'Romanian', code: 'ro' },
  { name: 'Russian', code: 'ru' },
  { name: 'Samoan', code: 'sm' },
  { name: 'Scots Gaelic', code: 'gd' },
  { name: 'Serbian', code: 'sr' },
  { name: 'Sesotho', code: 'st' },
  { name: 'Shona', code: 'sn' },
  { name: 'Sindhi', code: 'sd' },
  { name: 'Sinhala', code: 'si' },
  { name: 'Slovak', code: 'sk' },
  { name: 'Slovenian', code: 'sl' },
  { name: 'Somali', code: 'so' },
  { name: 'Spanish', code: 'es' },
  { name: 'Sundanese', code: 'su' },
  { name: 'Swahili', code: 'sw' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Tajik', code: 'tg' },
  { name: 'Tamil', code: 'ta' },
  { name: 'Telugu', code: 'te' },
  { name: 'Thai', code: 'th' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Uyghur', code: 'ug' },
  { name: 'Uzbek', code: 'uz' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Welsh', code: 'cy' },
  { name: 'Xhosa', code: 'xh' },
  { name: 'Yiddish', code: 'yi' },
  { name: 'Yoruba', code: 'yo' },
  { name: 'Zulu', code: 'zu' }
];

export const sttLanguages = [
    { name: '🌐 Detect Automatically', code: 'auto' },
    { name: 'Afrikaans (South Africa)', code: 'af-ZA' },
    { name: 'Arabic (Algeria)', code: 'ar-DZ' },
    { name: 'Arabic (Egypt)', code: 'ar-EG' },
    { name: 'Arabic (Saudi Arabia)', code: 'ar-SA' },
    { name: 'Arabic (UAE)', code: 'ar-AE' },
    { name: 'Bengali (India)', code: 'bn-IN' },
    { name: 'Bhojpuri (India)', code: 'bho-IN' },
    { name: 'Chinese (Mandarin, China)', code: 'zh-CN' },
    { name: 'Chinese (Mandarin, Taiwan)', code: 'zh-TW' },
    { name: 'Chinese (Cantonese, HK)', code: 'zh-HK' },
    { name: 'Czech (Czech Republic)', code: 'cs-CZ' },
    { name: 'Danish (Denmark)', code: 'da-DK' },
    { name: 'Dutch (Netherlands)', code: 'nl-NL' },
    { name: 'English (Australia)', code: 'en-AU' },
    { name: 'English (Canada)', code: 'en-CA' },
    { name: 'English (India)', code: 'en-IN' },
    { name: 'English (UK)', code: 'en-GB' },
    { name: 'English (US)', code: 'en-US' },
    { name: 'Filipino (Philippines)', code: 'fil-PH' },
    { name: 'Finnish (Finland)', code: 'fi-FI' },
    { name: 'French (France)', code: 'fr-FR' },
    { name: 'German (Germany)', code: 'de-DE' },
    { name: 'Greek (Greece)', code: 'el-GR' },
    { name: 'Gujarati (India)', code: 'gu-IN' },
    { name: 'Hindi (India)', code: 'hi-IN' },
    { name: 'Hungarian (Hungary)', code: 'hu-HU' },
    { name: 'Indonesian (Indonesia)', code: 'id-ID' },
    { name: 'Italian (Italy)', code: 'it-IT' },
    { name: 'Japanese (Japan)', code: 'ja-JP' },
    { name: 'Kannada (India)', code: 'kn-IN' },
    { name: 'Korean (South Korea)', code: 'ko-KR' },
    { name: 'Malay (Malaysia)', code: 'ms-MY' },
    { name: 'Malayalam (India)', code: 'ml-IN' },
    { name: 'Marathi (India)', code: 'mr-IN' },
    { name: 'Norwegian (Norway)', code: 'no-NO' },
    { name: 'Polish (Poland)', code: 'pl-PL' },
    { name: 'Portuguese (Brazil)', code: 'pt-BR' },
    { name: 'Portuguese (Portugal)', code: 'pt-PT' },
    { name: 'Punjabi (India)', code: 'pa-IN' },
    { name: 'Russian (Russia)', code: 'ru-RU' },
    { name: 'Spanish (Mexico)', code: 'es-MX' },
    { name: 'Spanish (Spain)', code: 'es-ES' },
    { name: 'Spanish (US)', code: 'es-US' },
    { name: 'Swedish (Sweden)', code: 'sv-SE' },
    { name: 'Tamil (India)', code: 'ta-IN' },
    { name: 'Telugu (India)', code: 'te-IN' },
    { name: 'Thai (Thailand)', code: 'th-TH' },
    { name: 'Turkish (Turkey)', code: 'tr-TR' },
    { name: 'Ukrainian (Ukraine)', code: 'uk-UA' },
    { name: 'Urdu (India)', code: 'ur-IN' },
    { name: 'Vietnamese (Vietnam)', code: 'vi-VN' }
];
